name: Secret

on: [workflow_dispatch, push]

jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
      -  name: Render case-insensitive Secret name
         run: echo "${{ secrets.ApiKey }}"
      -  name: Render upper-cased Secret name
         run: echo "${{ secrets.APIKEY }}"
      -  name: Render Secret as environment variable
         run: echo "${{ env.API_KEY }}"