name: Secret

on: [workflow_dispatch, push]

jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
      -  name: Render original Secret name
         run: echo "${{ secrets.ApiKey }}"
      -  name: Render Secret as environment variable
         run: echo "${{ env.APIKEY }}"